using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Photon.Pun;

public class CongelarRotaci贸n : MonoBehaviourPunCallbacks
{
    private Quaternion initialRotation;

    void Start()
    {
        if (photonView.IsMine)
        {
            initialRotation = transform.rotation;
        }                                           // Guardamos la rotaci贸n inicial del objeto hijo

    }

    void LateUpdate()
    {
        if (photonView.IsMine)
        {
            // Reseteamos la rotaci贸n del objeto hijo a su rotaci贸n inicial en cada frame
            transform.rotation = initialRotation;
        }
    }
}
